### ISSUE TITLE
not loading code in web page

### ISSUE THREAD

**Issue by alex9green** [missing-user/heat-pump-dashboard#17]
heat-pump-dashboard/co2intensity.py:6: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

/usr/local/lib/python3.12/dist-packages/meteostat/core/loader.py:82: FutureWarning:

Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.

/usr/local/lib/python3.12/dist-packages/meteostat/core/loader.py:82: FutureWarning:

Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.

/usr/local/lib/python3.12/dist-packages/meteostat/core/loader.py:82: FutureWarning:

Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.

/usr/local/lib/python3.12/dist-packages/meteostat/core/loader.py:82: FutureWarning:

Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.

/usr/local/lib/python3.12/dist-packages/meteostat/interface/meteodata.py:167: FutureWarning:

'H' is deprecated and will be removed in a future version, please use 'h' instead.

/home/delta/heat-pump-dashboard/co2intensity.py:6: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

**Comment by alex9green** [comment]
co2intensity.py 
/home/delta/hplib/heat-pump-dashboard/co2intensity.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  hour_deltas = pd.to_datetime(power_df["Start"]).dt.hour.apply(
/home/delta/hplib/heat-pump-dashboard/co2intensity.py:9: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  power_df["Date"] = pd.to_datetime(power_df["Date"],infer_datetime_format=False) + hour_deltas

**Comment by alex9green** [comment]
Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
Traceback (most recent call last):
  File "/home/delta/hplib/heat-pump-dashboard/datasource.py", line 78, in <module>
    print(fetch_all("DE", 81829, "2020-01-01", "2022-01-02", "Somm"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delta/hplib/heat-pump-dashboard/datasource.py", line 59, in fetch_all
    df = temperatures.load_TRY(TRY_dataset).rename(
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'temperatures' has no attribute 'load_TRY'

**Comment by alex9green** [comment]
trydf["Date"] = pd.to_datetime(
            dict(
                year=trydf["year"], month=trydf["MM"], day=trydf["DD"], hour=trydf["HH"]
            ), format="%Y-%m-%d %H:%M:%S"
        )

**Comment by alex9green** [comment]
we don`t have this folders ....no update informations 
csv missing

hplib_database.py

THIS_FOLDER_PATH + "/../input/csv/" + filename + ".csv"
 
 df = pd.read_csv("../output/database_reduced.csv")

df = pd.read_csv("data/hplib_database.csv", delimiter=",")


"https://www.heatpumpkeymark.com/?type=109126").content,
        "html.parser",   we need update models
