### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alex9green** [missing-user/heat-pump-dashboard#18]
$ /usr/local/bin/python /workspaces/emulator/heatings.py
Traceback (most recent call last):
  File "/workspaces/emulator/heatings.py", line 183, in <module>
    simulate_hp(pd.read_csv("test_data.csv"), model="Bosch Compress 3000 AWS-8 B")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test_data.csv'

**Comment by alex9green** [comment]
$ /usr/local/bin/python /workspaces/emulator/datasource.py
UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
Fetching from https://re.jrc.ec.europa.eu/api/v5_2/seriescalc {'lat': np.float64(48.1404), 'lon': np.float64(11.6802), 'startyear': 2019, 'endyear': 2020, 'components': '0', 'outputformat': 'csv', 'angle': 90, 'aspect': 0}
Fetching from https://re.jrc.ec.europa.eu/api/v5_2/seriescalc {'lat': np.float64(48.1404), 'lon': np.float64(11.6802), 'startyear': 2019, 'endyear': 2020, 'components': '0', 'outputformat': 'csv', 'angle': 90, 'aspect': -90}
Fetching from https://re.jrc.ec.europa.eu/api/v5_2/seriescalc {'lat': np.float64(48.1404), 'lon': np.float64(11.6802), 'startyear': 2019, 'endyear': 2020, 'components': '0', 'outputformat': 'csv', 'angle': 90, 'aspect': 90}
                     T_outside [°C]  ...  Other conventional [%]
2020-01-01 00:00:00             1.7  ...                4.417002
2020-01-01 01:00:00             0.6  ...                4.355073
2020-01-01 02:00:00             1.8  ...                4.122084
2020-01-01 03:00:00             1.1  ...                4.090353
2020-01-01 04:00:00             0.1  ...                4.136084
...                             ...  ...                     ...
2022-01-01 20:00:00             7.5  ...                2.910307
2022-01-01 21:00:00             7.1  ...                2.995440
2022-01-01 22:00:00             5.1  ...                3.002150
2022-01-01 23:00:00             4.0  ...                3.115688
2022-01-02 00:00:00             3.3  ...                3.225432

[17569 rows x 17 columns]
UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
Traceback (most recent call last):
  File "/workspaces/emulator/datasource.py", line 78, in <module>
    print(fetch_all("DE", 81829, "2020-01-01", "2022-01-02", "Somm"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/emulator/datasource.py", line 59, in fetch_all
    df = temperatures.load_TRY(TRY_dataset).rename(
         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'temperatures' has no attribute 'load_TRY'
 /workspaces/emulator (main) $
